language: python 
python:
  - "3.7"
  - "3.8"
sudo: false
cache: pip
dist: bionic
matrix:
  include:
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38
    - python: 3.8-dev
      env: TOXENV=py38
install:
  - pip install -r requirements.txt
# command to run tests
script: python peerfinder/peerfinder.py --asn 6507 15133 --ix
